/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.conectar;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author  ELIÀN R.
 */
public class formulario extends javax.swing.JFrame {
    
    conectar conecto;
    
    PreparedStatement ps;
    ResultSet rs;
    
     private static Connection conn; 
    private static final String driver = "com.mysql.jdbc.Driver";
    private static final String user = "root";
    private static final String pass = "";
    private static final String url = "jdbc:mysql://localhost:3306/micarpinteria";
    
    public formulario (){
        initComponents();
    }
    
    //este metodo nos retorna la conexion 
    public Connection getConnection (){
        
        Connection conn = null; 
        try {
            Class.forName(driver);
            conn = DriverManager.getConnection (url, user, pass);
        if (conn != null){
            System.out.println ("La conexión se estalecio bien con la DB");
            }
        } catch (ClassNotFoundException | SQLException e){
            System.out.println ("Error al conectar con la BD" + e);
        }
        return conn;
        
    }
    
    //metodo para desconectar 
    public void desconectar (){
        conn = null;
        if (conn == null){
            System.out.println ("Se desconecto de la DB");
        }
    }
    
    
    public void borrarCajas (){
     CajaNombre.setText(null);
     CajaDocumento.setText(null);
     CajaDireccion.setText(null);
     CajaTelefono.setText(null);
     CajaCorreo.setText(null);
    
    }

    /**
     * Creates new form formulario
     *

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CajaNombre = new javax.swing.JTextField();
        CajaDocumento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Bconectar = new javax.swing.JButton();
        Bdesconectar = new javax.swing.JButton();
        Benviar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CajaDireccion = new javax.swing.JTextField();
        CajaCorreo = new javax.swing.JTextField();
        CajaTelefono = new javax.swing.JTextField();
        jlLogo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 110, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Documento ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        CajaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaNombreActionPerformed(evt);
            }
        });
        getContentPane().add(CajaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 280, 30));

        CajaDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaDocumentoActionPerformed(evt);
            }
        });
        getContentPane().add(CajaDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 280, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText(" INGRESA TUS DATOS");
        jLabel4.setAutoscrolls(true);
        jLabel4.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 200, 30));

        Bconectar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bconectar.setText("CONECTAR ");
        Bconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BconectarActionPerformed(evt);
            }
        });
        getContentPane().add(Bconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 140, 40));

        Bdesconectar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bdesconectar.setText("DESCONECTAR");
        Bdesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdesconectarActionPerformed(evt);
            }
        });
        getContentPane().add(Bdesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 150, 40));

        Benviar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Benviar.setText("ENVIAR");
        Benviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BenviarActionPerformed(evt);
            }
        });
        getContentPane().add(Benviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, 110, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Dirección:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Correo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Teléfono:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, -1));
        getContentPane().add(CajaDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 280, 30));
        getContentPane().add(CajaCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 280, 30));

        CajaTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(CajaTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 280, 30));

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logito.png"))); // NOI18N
        getContentPane().add(jlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 160, 130));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("CARPINTERÍA Spark.Table");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/madera.jpg"))); // NOI18N
        getContentPane().add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CajaDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaDocumentoActionPerformed

    private void CajaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaNombreActionPerformed

    //Comportamiento del boton 
    
    private void BconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BconectarActionPerformed
        conecto = new conectar ();
        Connection reg = conecto.getConnection ();
    }//GEN-LAST:event_BconectarActionPerformed

    private void BdesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdesconectarActionPerformed
        conecto.desconectar ();
    }//GEN-LAST:event_BdesconectarActionPerformed

    private void BenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BenviarActionPerformed
      Connection conn = null;
      
        try {
            conn = getConnection();
            ps = conn.prepareStatement("INSERT INTO datos (nombre, documento, direccion, telefono, email, fechareg)VALUES (?,?,?,?,?,?)");
            ps.setString(1, CajaNombre.getText());
            ps.setInt(2, 1007383715);
            ps.setString(3,CajaDireccion.getText());
            ps.setInt(4, 102641138);
            ps.setString(5, CajaCorreo.getText());
            ps.setDate(6, Date.valueOf(LocalDate.now()));
            
            int result = ps.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Los datos fueron enviados correctamente");
                borrarCajas ();
                
            }else{
                JOptionPane.showMessageDialog(null, "Los datos no fueron enviados");
              }
            conn.close ();
            
        } catch (Exception e) {
            System.out.println (e);
        }
    }//GEN-LAST:event_BenviarActionPerformed

    private void CajaTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaTelefonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bconectar;
    private javax.swing.JButton Bdesconectar;
    private javax.swing.JButton Benviar;
    private javax.swing.JTextField CajaCorreo;
    private javax.swing.JTextField CajaDireccion;
    private javax.swing.JTextField CajaDocumento;
    private javax.swing.JTextField CajaNombre;
    private javax.swing.JTextField CajaTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jlFondo;
    private javax.swing.JLabel jlLogo;
    // End of variables declaration//GEN-END:variables
}
